memory_map:
  ram:  {base_addr:  0x20000000, size: 0x00400000, permissions: rwx}
  mmio: {base_addr:  0x40000000, size: 0x20000000, permissions: rw-}
  peripheral_ram: {base_addr:  0x60000000, size: 0x40000000, permissions: rw-}
  peripheral: {base_addr:  0xa0000000, size: 0x40000000, permissions: rw-}
  nvic: {base_addr:  0xe0000000, size: 0x10000000, permissions: rw-}
  irq_ret: {base_addr: 0xfffff000, size: 0x1000, permissions: rwx} 
initial_sp: 0x20014000

handlers:
  HAL_Delay: do_return
  Delay: do_return
  wait: do_return
  wait_us: do_return